SELECT 
    PRODUCT,
    CATEGORY,
    QUANTITY,
    SALES_AMOUNT,
    CUSTOMER_NAME,
    AGE,
    CONTACT,
    EMPLOYEE,
    DESIGNATION,
    BRANCH,
    BRANCH_CODE,
    DATE,
    DAY
 
    FROM {{source('BHATBHATENI_MODELING','BHATBHATENI_STAGE_TABLE') }}