SELECT 
    PRODUCT,
    CATEGORY,
    QUANTITY,
    SALES_AMOUNT,
    CUSTOMER_NAME,
    AGE,
    CONTACT,
    EMPLOYEE,
    DESIGNATION,
    BRANCH,
    CITY,
    DATE,
    DAY,
    GETDATE() AS LOAD_DATE
 
    FROM {{source('BHATBHATENI_MODELING','BHATBHATENI_STAGE_TABLE') }}