version: 2

sources:
  - name: BHATBHATENI_MODELING
    database: STAGING_DB
    schema: PUBLIC
    tables:
      - name: BHATBHATENI_STAGE_TABLE
        columns:
          - name: CONTACT
            tests:
              - not_null
              - unique
          - name: BRANCH
            tests:
              - accepted_values:
                  values: ['BAGMATI', 'PROVINCE-1']    

